### ISSUE TITLE
Landing page for the portofolio website

### ISSUE THREAD

**Issue by Deepankar1484** [Mozilla-Campus-Club-Cummins/Design_HacktoberFest24#15]
Hey @SnehalMeshram09,
I, Deepankar garg, will be really greatfull to you, if you assign me the work. Just assign me the task with the hacktoberfest accepted label.
Thank you,
Deepankar Garg

**Comment by divyaaa16** [comment]
hi, I would love to work on this issue .Can you please assign it to me?

**Comment by Krutika3075** [comment]
Hello, I'm Krutika Pingale , CCEW SY ENTC,
I want to work on this issue, could you please assign it to me.

**Comment by Deepankar1484** [comment]
Hey @SnehalMeshram09, Please assign me the task. I will complete my work in 24 hours of assigning.

**Comment by HarshadaSonje** [comment]
Hello, @Deepankar1484  . Contributions to this repository are restricted to CCOEW students only. For more information, please refer to the Readme.md.

**Comment by Deepankar1484** [comment]
Closing the issue due to restrictions on the repository.
Thank you, 
Deepankar Garg
