### ISSUE TITLE
design creative footer/End page for portfolio website

### ISSUE THREAD

**Issue by divyaaa16** [Mozilla-Campus-Club-Cummins/Design_HacktoberFest24#16]

**Comment by MUDITJAINN** [comment]
Please assign this issue to me under hactoberfest2024

**Comment by divyaaa16** [comment]
Hi @MUDITJAINN  I appreciate your participation but, Contributions to this repository are restricted to CCOEW students only.

**Comment by MUDITJAINN** [comment]
Okay I didn't saw that earlier.
